### ISSUE TITLE
go install ecr credential is killing and time consuming -do we have python version of this util?

### ISSUE THREAD

**Issue by mkaja** [awslabs/amazon-ecr-credential-helper#133] opened 2018-12-03 03:38 UTC
go install ecr credential is killing and time consuming -do we have python version of this util?

 setting gopath and goroot in both linux and mac is killing ....

**Comment by estahn** [comment] 2018-12-28 04:54
@mkaja This is a duplicate of #80 

If this is for your local the following may be helpful: https://github.com/awslabs/amazon-ecr-credential-helper/issues/80#issuecomment-376140958

**Comment by samuelkarp** [comment] 2019-07-06 00:11
Closing in favor of https://github.com/awslabs/amazon-ecr-credential-helper/issues/80

**Closed by samuelkarp** 2019-07-06 00:11 UTC
