### ISSUE TITLE
Unable to use on Mac OS High Sierra, produces "Segmentation fault: 11"

### ISSUE THREAD

**Issue by unicron** [awslabs/amazon-ecr-credential-helper#70] opened 2017-09-28 19:39 UTC
Upgraded to Mac OS High Sierra, and now unable to run this binary.  Was working fine before the upgrade, but now seems broken.  Have tried recompiling and same result.  Any ideas?

Log in via docker login works fine.

**Comment by samuelkarp** [comment] 2017-09-28 20:23
Looks like this is a duplicate of https://github.com/awslabs/amazon-ecr-credential-helper/issues/69.  Can you try rebuilding the binary as was recommended in that issue?

**Comment by unicron** [comment] 2017-09-28 21:36
I did try that using the Docker image, with same result.  I’ll check again.

**Comment by samuelkarp** [comment] 2017-09-28 21:37
@unicron If you have the Go toolchain installed on your Mac, can you try that too?  I think this might be related to https://github.com/golang/go/issues/22059.

**Comment by unicron** [comment] 2017-09-28 22:30
I could try that, but I'm unsure how to do that... I have go installed via brew, but not sure where or what to run in order to compile from source.  Looked at the Docker and Make files haven't made sense of it yet.

**Comment by samuelkarp** [comment] 2017-10-02 18:01
@unicron Check out the source code into your `GOPATH` under the directory `github.com/awslabs/amazon-ecr-credential-helper` (so if your `GOPATH` is `~/go`, you'd check it out to `~/go/src/github.com/awslabs/amazon-ecr-credential-helper`) and then run `make` from that directory.  You should end up with a binary in `bin/local` that you can then try.

**Comment by unicron** [comment] 2017-10-02 18:43
Ah, working now!  Thank you.

**Closed** 2017-10-02 19:01 UTC

**Comment by fengyanliang** [comment] 2017-11-21 02:56
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
./scripts/build_binary.sh: line 36: 92476 Segmentation fault: 11  GOOS=$TARGET_GOOS GOARCH=$TARGET_GOARCH CGO_ENABLED=0 go build -installsuffix cgo -a -ldflags '-s' -o $1/docker-credential-ecr-login ./ecr-login/cli/docker-credential-ecr-login
make: *** [bin/local/docker-credential-ecr-login] Error 139
