### ISSUE TITLE
Create a Docker image containing the ECR credential helper

### ISSUE THREAD

**Issue by tomelliff** [awslabs/amazon-ecr-credential-helper#56] opened 2017-08-11 09:09 UTC
I'm using Gitlab CI and we have previously been using shell executors to build Docker images but have decided to move over to using docker executors and bind-mounting the Docker socket into the CI container.

This is great but it means we now need the CI container to be able to authenticate with ECR and thus either need to run the `eval $(aws ecr get-login --no-include-email)` command and have the AWS CLI available to the container or we need to use the ECR credential helper.

For now I've created a simple Docker image based off `docker:latest` with the credential helper binary in it but it would be great if we could just pull this directly off Docker Hub (like the `amazonlinux` image) instead of having to keep it in yet another ECR repo.

I could push it to Docker Hub myself but I'd guess most people would prefer an official image instead.

For reference the Dockerfile was simply:

```dockerfile
FROM docker:latest

COPY docker-credential-ecr-login /usr/local/bin/
COPY config.json /root/.docker/config.json
```

Although it would probably make sense to use [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds) from this repo to make it much simpler to build.

**Comment by samuelkarp** [comment] 2017-08-11 17:26
Thanks for reaching out.  I'm going to close this as a duplicate of https://github.com/awslabs/amazon-ecr-credential-helper/issues/15, which is already tracking the request for released binaries.

**Closed by samuelkarp** 2017-08-11 17:26 UTC
