### ISSUE TITLE
Failure in authentication when `credStore` is set

### ISSUE THREAD

**Issue by WhyNotHugo** [awslabs/amazon-ecr-credential-helper#214] opened 2020-05-17 19:08 UTC
I'm using `credStore` by default for my docker.io credentials, but want to use this helper for AWS only.

However, the following does not seem to work:

```
{
        "credsStore": "secretservice",
	"credHelpers": {
		"*.dkr.ecr.*.amazonaws.com": "ecr-login"
	}
}
```

Returns:

```
ERROR: for availability-fixtures  Get "https://129317782449.dkr.ecr.eu-west-1.amazonaws.com/v2/REDACTED/manifests/master": no basic auth credentials
```

Is this an issue with the helper or a docker issue?

**Comment by czechnology** [comment] 2020-06-24 09:01
I seem to have similar issues even when setting the default `credsStore` (btw, note the two S's). I can pull the image but when I try to run the docker build, it fails on the FROM directive while trying to get the `..REGISTRY../v2/..IMAGE../manifests/latest` with `no basic auth credentials`.

The weird thing is that `~/.ecr/cache.json` appears but never a log file in the same dir (as per the docs).

**Comment by skyzyx** [comment] 2020-07-21 20:48
Using the latest version, this worked for me:

```json
{
  "credHelpers": {
    "{account}.dkr.ecr.{region}.amazonaws.com": "ecr-login"
  }
}
```

**Comment by samuelkarp** [comment] 2020-12-22 19:34
Hi @WhyNotHugo! Docker does not support wildcards in the `credHelpers` section of `~/.docker/config.json`. This will need to be a feature request on the Docker side. Since this is not a bug or feature request in the credential helper itself, I'm going to close this issue.

**Closed by samuelkarp** 2020-12-22 19:34 UTC
