### ISSUE TITLE
Relax the restriction docker-credential-ecr-login can only be used with Amazon Elastic Container Registry.

### ISSUE THREAD

**Issue by iNikem** [awslabs/amazon-ecr-credential-helper#193] opened 2019-12-12 14:07 UTC
We use AWS ECR through our internal proxy, which provides much more user-friendly dns name "docker.company.com" for this Docker Registry. Unfortunately, docker-credential-ecr-login fails in this case with "docker-credential-ecr-login can only be used with Amazon Elastic Container Registry."

Can this restriction be lifted?

**Comment by samuelkarp** [comment] 2019-12-31 00:51
Closing as a duplicate of https://github.com/awslabs/amazon-ecr-credential-helper/issues/94.  You may also be interested in following https://github.com/aws/containers-roadmap/issues/299, which tracks the general custom domain feature for ECR.

**Closed by samuelkarp** 2019-12-31 00:51 UTC
